### ISSUE TITLE
Ability to analyze sosreport or foreman-debug

### ISSUE THREAD

**Issue by waldirio** [waldirio/sos_analyze#11]
Ability to analyze both kind of log

**Comment by meteryam** [comment]
i've posted a code idea in the meteryam branch.

**Comment by waldirio** [comment]
closing it.
Thank you @meteryam !!!

**Comment by meteryam** [comment]
thank you!


Regards,


Jessica Richards

She/Her/Hers 🏳️‍⚧

STSE

Red Hat <https://www.redhat.com/>
<https://www.redhat.com/>
