### ISSUE TITLE
check dynflow executor count for tuning

### ISSUE THREAD

**Issue by pdudley** [waldirio/sos_analyze#63]
╰─ grep EXECUTORS_COUNT sosreport-satellite-TS003122017-2020-02-13-bvraydo/etc/sysconfig/dynflowd
#EXECUTORS_COUNT=1

**Comment by waldirio** [comment]
Paul, currently, we have this information on diff section (dynflow), however, I agree with you that will be really useful on tuning section.

Thanks for the heads up. Doing it.
