### ISSUE TITLE
sos-analyze.sh missing from /tmp/script

### ISSUE THREAD

**Issue by gctaylor1pers** [waldirio/sos_analyze#7]
Is this intentional?  I have downloaded a copy to my $HOME dir as a workaround.

**Comment by waldirio** [comment]
Hi

Could you please copy/paste the complete issue or backtrace?

I didn't follow, I'm not sure if you are seeing an issue or not.

Thank you.

**Comment by patalber** [comment]
[supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:21+0000]
[patalber@supportshell ~]$ cd /tmp/script/
[supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:29+0000]
[patalber@supportshell script]$ ll
total 0
[supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:31+0000]
[patalber@supportshell script]$ 

It seems that the script is missing from supportshell.

**Comment by waldirio** [comment]
> [supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:21+0000]
> [patalber@supportshell ~]$ cd /tmp/script/
> [supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:29+0000]
> [patalber@supportshell script]$ ll
> total 0
> [supportshell.prod.useraccess-us-west-2.redhat.com] [21:15:31+0000]
> [patalber@supportshell script]$
> 
> It seems that the script is missing from supportshell.

Done.

Thanks for the heads up.
