### ISSUE TITLE
paused tasks on foreman

### ISSUE THREAD

**Issue by waldirio** [waldirio/sos_analyze#96]

**Comment by JaskaranNarula** [comment]
@waldirio 
This might sound silly but what issue we are looking at this step?

**Comment by waldirio** [comment]
@JaskaranNarula not silly at all. Just to confirm what task is still paused, the root cause could be the main one. For example, once dynflow is down, the tasks will be in the queue waiting and eventually, I believe they will be stopped and/or paused with some diff/weird status.

Thank you!

Ps.: Already implemented!
